version: '3.8'

services:
  app:
    container_name: front-prod
    build: .
    ports:
      - "8081:8081"   # Metro bundler
      - "19000:19000" # Expo DevTools
      - "19001:19001" # Expo
      - "19002:19002" # Expo
    environment:
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
    volumes:
      - .:/app
      - /app/node_modules
    stdin_open: true
    tty: true 