version: '3.8'

services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: dev.dockerfile
    ports:
      - "8080:8080"
      - "35729:35729"  # LiveReload port
    volumes:
      - ./src:/app/src
      - ./pom.xml:/app/pom.xml
      - ~/.m2:/root/.m2  # Maven cache
      - ./src/main/resources:/app/src/main/resources
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=dev

  db:
    image: postgres:15
    container_name: db
    ports:
      - "5432:5432"
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d
      - postgres_data_dev:/var/lib/postgresql/data
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data_dev: 